-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.carpetas
(
    id_carpeta integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_carpeta character varying(50) COLLATE pg_catalog."default" NOT NULL DEFAULT 'Nueva carpeta'::character varying,
    fecha_creacion_carpeta timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_edicion_carpeta timestamp without time zone,
    CONSTRAINT carpetas_pkey PRIMARY KEY (id_carpeta)
);

CREATE TABLE IF NOT EXISTS public.notas
(
    id_nota integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombre_nota character varying COLLATE pg_catalog."default" NOT NULL DEFAULT 'Nueva nota'::character varying,
    fecha_creacion_nota timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    fecha_edicion_nota timestamp without time zone,
    descripcion_nota text COLLATE pg_catalog."default",
    usuario_editor_nota integer NOT NULL,
    archivada boolean NOT NULL,
    fk_id_carpeta integer NOT NULL,
    CONSTRAINT notas_pkey PRIMARY KEY (id_nota)
);

COMMENT ON TABLE public.notas
    IS 'Tabla que almacena las notas';

COMMENT ON COLUMN public.notas.id_nota
    IS 'Identificador único autoincremental de la nota';

COMMENT ON COLUMN public.notas.nombre_nota
    IS 'Nombre de la nota';

CREATE TABLE IF NOT EXISTS public.usuarios
(
    id_usuario integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    nombres_usuario character(50) COLLATE pg_catalog."default" NOT NULL,
    apellidos_usuario character(50) COLLATE pg_catalog."default" NOT NULL,
    correo_usuario character varying(50) COLLATE pg_catalog."default" NOT NULL,
    clave_usuario character varying(50) COLLATE pg_catalog."default" NOT NULL,
    imagen_usuario text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT usuario_pkey PRIMARY KEY (id_usuario)
);

CREATE TABLE IF NOT EXISTS public.usuarios_carpetas
(
    usuarios_id_usuario integer NOT NULL,
    carpetas_id_carpeta integer NOT NULL,
    propietario boolean NOT NULL,
    editor boolean
);

CREATE TABLE IF NOT EXISTS public.usuarios_notas
(
    usuarios_id_usuario integer NOT NULL,
    notas_id_nota integer NOT NULL,
    propietario boolean NOT NULL,
    editor boolean
);

COMMENT ON COLUMN public.usuarios_notas.notas_id_nota
    IS 'Identificador único autoincremental de la nota';

ALTER TABLE IF EXISTS public.usuarios_carpetas
    ADD CONSTRAINT usuarios_carpetas_carpetas_id_carpeta_fkey FOREIGN KEY (carpetas_id_carpeta)
    REFERENCES public.carpetas (id_carpeta) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios_carpetas
    ADD CONSTRAINT usuarios_carpetas_usuarios_id_usuario_fkey FOREIGN KEY (usuarios_id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios_notas
    ADD CONSTRAINT usuarios_notas_notas_id_nota_fkey FOREIGN KEY (notas_id_nota)
    REFERENCES public.notas (id_nota) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.usuarios_notas
    ADD CONSTRAINT usuarios_notas_usuarios_id_usuario_fkey FOREIGN KEY (usuarios_id_usuario)
    REFERENCES public.usuarios (id_usuario) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;